export const ROUTES = {
    ATTRIBUTE: '/attribute',
    ATTRIBUTE_VALUE: '/attribute-value',
    CATEGORY: '/category',
    DASHBOARD: '/dashboard',
    INVENTORY: '/inventory',
    LOGIN: '/login',
    ORDER: '/order',
    PAYMENT: '/payment',
    PRODUCT: '/product',
    STATISTIC: '/statistic',
    STATISTIC_ORDER: '/statistic/order',
    STATISTIC_PRODUCT: '/statistic/product',
    STATISTIC_REVENUE_PROFIT: '/statistic/revenue-profit',
    STATISTIC_STOCK: '/statistic/stock',
    STATISTIC_USER: '/statistic/user',
    WAREHOUSE: '/warehouse',
  };